def compl(args):
    output = ''
    for c in args:
        if (c == 'A'):
            output += 'T'
        elif (c == 'T'):
            output += 'A'
        elif (c == 'C'):
            output += 'G'
        else:
            output += 'C'
    return output

def fun(args, length):
    index  = 0
    for c in args:
        if ((index + length) > len(args)):
            return
        word = args[index:index+length]
        if (word[::-1] == compl(word)):
            print (index+1), length
        index+= 1

if __name__ == '__main__':
    data = 'TATAGGTAGTACCAGATCTCCGACTCTGTAGCTCAGAGGTTCCTGTAACGTCCCGGTACACATCCTAGAATTCGTTGAGCAGAACCACCCCTCGCGGTTCGAGGACCAGTTAGAAACTCGAAAAGACGTAGATAAGCGGGGAGCTCATGAGCAATGCAGAGACGAGGAGGGGCAATGTGGCATTCAATAGCCTTAACCATATCCGGATCGAGGGCTATGTAATGTAGAGGGCATGATGTTTGTCGGACGCCAGGAACAACTCCGTTGTACGACGAGCATCTAAGTAAAACAAGATTCTGGATGAAGACCAAAAGTCGAGATGGGGCCGGCATAAGGCTCGACACCCTGTTATTCTGACCTACATGTCATGGGTATGAAAGGTCAGAGACTCGTCGTTGCCGGGCCTGATGGTAGGCTGCAGCCTAATGGCATGTGAGTCACTCCCTTCACCCGTACCACGCCGTATGCTCACTTTGGGATGATAATTGTGACCGTAGCATCTGCATGCCATGTATGGCCGAGCAGGCCTTGTGCGCAGGATTCAAACATCAATTCAATCAAGACAGAACCGGGGGGGAAACGAGCACCTTGTGCGTGGACGTAGAAGAGGACACCCTCGACTTCTGTCTAGACTACTGAATTTTCCTTGTGAAGAGGATGTAAGACTCCCTCTAGACCAACGCCTCCGCTGTCGTCTAACCTTCTCGCACTTTTGCTTACTTCCCCCAGTCAAGCCGCGTCCACGTAGTGGTTGTAATACTTTACGCTATTTCGCAACACCGACAGGACCAAGACGTGGGCCCTAGTTCACCATTACCGTTTGCATACATAAATAT'
    for i in range(4, 13):
        fun(data, i)

