if __name__ == '__main__':
    data = '''
CAAAAGAGACAAAAGACCAAAAGACAAAAGACTGGCGAGACAAAAGACAAAAGAACAAAAGAATTGTCAAAAGATCAAAAGACCATTAACCGGGTACAAAAGACCAAAAGAGATGCAAAAGACGCCCGAGTGAAGCAAAAGAACAAAAGAGGCAAAAGACAAAAGATTTCAAAAGACAAAAGATTCAAAAGAAACAAAAGAACAAAAGACCGCACAAAAGAGCAATCAAAAGAGAACAAAAGACCGCAAAAGAGTACAAAAGAAGCAAAAGACAAAAGACAAAAGACACCCAAAAGATGATCAAAAGACAAAAGAACAAAAGATCGGTTTCCAAAAGACAAAAGACGCGCCTCAAAAGACGCAAAAGACCCAAAAGACAAAAGAACGCAGCAAAAGACAAAAGAGCAAAAGACAAAAGATGCAAAAGATTCGAGCAAAAGATGCGTTGATCGCCCCCTCACGCAAAAGACTTACGCCAGCCAAAAGACTCAAAAGAGGACAGACAAAAGATACTACTTTCAAAAGATCAAAAGAGCAAAAGACGGATAGGCCCAAAAGACAAAAGATACGGCCCCACAAAAGACACAACCAAAAGAGCAAAAGAATCAAAAGACAAAAGATCCAAAAGATCAAAAGATCAAAAGAGCAAAAGACCAAAAGAACAAAAGAAGACCCAAAAGACTGGGACAAAAGACTTCCTCCAAAAGAAGCAAAAGACAAAAGATTCAAAAGAGCAAAAGACAAAAGAGTTACAAAAGAATCAAAAGACAAAAGAGGTCAAAAGAGACAAAAGACAAAAGACAAAAGATTACAAAAGACAAAAGATCAAAAGACCAAAAGATTTGCAAAAGAATGACACCAAAAGACAAAAGACAAAAGATCACACAAAAGAACAAAAGAGGACAAAAGACACAAAAGAACCCAAAAGAGCAAAAGAACAAAAGA
CAAAAGACA
'''
    args = filter(None, data.split('\n'))
    index = args[0].find(args[1])
    while (index != -1 and index < len(args[0])):
        print (index+1), 
        index = args[0].find(args[1], index+1)
    pass